// <auto-generated />
using System;
using API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241119141811_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("API.Model.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEmployee");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            IdEmployee = 1,
                            Birthday = new DateTime(2003, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.fourniat@viacesi.fr",
                            FirstName = "Laura",
                            LastName = "Fourniat",
                            PhoneNumber = "0678627362"
                        },
                        new
                        {
                            IdEmployee = 2,
                            Birthday = new DateTime(2005, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rafael.marsico@viacesi.fr",
                            FirstName = "Rafaël",
                            LastName = "Marsico",
                            PhoneNumber = "0628378210"
                        },
                        new
                        {
                            IdEmployee = 3,
                            Birthday = new DateTime(2001, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "simon.vende@viacesi.fr",
                            FirstName = "Simon",
                            LastName = "Vendé",
                            PhoneNumber = "0673827382"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
